version: '3.3'
services:
  db:
    container_name: loki_mysql
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_DATABASE: 'lokiapidb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lokiapiuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lokiapipass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lokiapipass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3387:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  api:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8888:8787